require: rubocop-performance

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - node_modules/**/*

LineLength:
  Max: 120

ConditionalAssignment:
  Enabled: false
StringLiterals:
  Enabled: false
RedundantReturn:
  Enabled: false
Documentation:
  Enabled: false
WordArray:
  Enabled: false
AbcSize:
  Enabled: false
MutableConstant:
  Enabled: false
SignalException:
  Enabled: false
Casecmp:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
MissingRespondToMissing:
  Enabled: false
MethodMissingSuper:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false


Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: True
  Exclude:
    - test/test_helper.rb
